### ISSUE TITLE
Dealing with velocities in ncmc

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/protons#44]
As @gregoryross points out, we have to reset velocities to original values upon rejecting. Currently, we only change their sign on acceptance.

**Comment by jchodera** [comment]
For NCMC, unless we draw the initial velocities from a Maxwell-Boltzmann distribution, we have to negate the velocities either on acceptance or rejection. Either choice is acceptable, as long as we do it the same way all the time.

Negating velocities can slow down sampling. Because we expect that acceptance is rarer than rejection, I suggest we negate upon rejection.

To summarize:

If accept:
* keep new velocities, new positions
* set velocities = - velocities

If reject:
* set velocities = old velocities 
* set positions = old positions

**Comment by bas-rustenburg** [comment]
Just wanted to chime in on this old issue,

I don't think this is fixed yet:
https://github.com/choderalab/protons/blob/master/protons/driver.py#L1131

**Comment by gregoryross** [comment]
@bas-rustenburg, it looks like you reverse velocities upon acceptance [here](https://github.com/choderalab/protons/blob/master/protons/driver.py#L1145), which seems fine.

**Comment by bas-rustenburg** [comment]
Yes, but we don't restore old velocities on reject.

**Comment by gregoryross** [comment]
Oh, you're right!

**Comment by bas-rustenburg** [comment]
I think we need to add 

`context.setVelocities(initial_velocities)`

**Comment by bas-rustenburg** [comment]
Which I will do at the next opportunity.

**Comment by bas-rustenburg** [comment]
Fixed in #76
